name: Go Build Multi-Platform

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        goos: [linux, windows, darwin, freebsd, openbsd, netbsd]
        goarch: [amd64, arm64, arm, 386, ppc64le, riscv64]
        exclude:
          - goos: windows
            goarch: ppc64le
          - goos: windows
            goarch: riscv64
          - goos: windows
            goarch: arm
          - goos: darwin
            goarch: 386
          - goos: darwin
            goarch: ppc64le
          - goos: darwin
            goarch: riscv64
          - goos: darwin
            goarch: arm
          - goos: freebsd
            goarch: arm64
          - goos: freebsd
            goarch: ppc64le
          - goos: freebsd
            goarch: riscv64
          - goos: openbsd
            goarch: arm64
          - goos: openbsd
            goarch: ppc64le
          - goos: openbsd
            goarch: riscv64
          - goos: netbsd
            goarch: arm64
          - goos: netbsd
            goarch: ppc64le
          - goos: netbsd
            goarch: riscv64

    runs-on: ubuntu-latest

    outputs:
      build_complete: ${{ steps.build_step.outcome == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Build Main Application
      id: build_step
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        # Set GOARM=6 for Raspberry Pi Zero compatibility when building for ARM
        GOARM: ${{ matrix.goarch == 'arm' && '6' || '' }}
      run: |
        cd gps-timesync
        output_name="gps-timesync-${GOOS}-${GOARCH}"
        if [ "$GOOS" = "windows" ]; then
          output_name+=".exe"
        fi
        go build -v -ldflags="-s -w" -o "../${output_name}" .
        echo "Built: ${output_name}"

    - name: Build Simulator
      id: build_simulator
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        GOARM: ${{ matrix.goarch == 'arm' && '6' || '' }}
      run: |
        cd gps-simulator
        output_name="gps-simulator-${GOOS}-${GOARCH}"
        if [ "$GOOS" = "windows" ]; then
          output_name+=".exe"
        fi
        go build -v -ldflags="-s -w" -o "../${output_name}" simulator.go
        echo "Built: ${output_name}"

    - name: Upload Main Application Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gps-timesync-${{ matrix.goos }}-${{ matrix.goarch }}
        path: gps-timesync-${{ matrix.goos }}-${{ matrix.goarch }}*

    - name: Upload Simulator Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gps-simulator-${{ matrix.goos }}-${{ matrix.goarch }}
        path: gps-simulator-${{ matrix.goos }}-${{ matrix.goarch }}*

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      contents: write

    steps:
      - name: Download All Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./release-assets

      - name: List downloaded files (for debugging)
        run: ls -R ./release-assets

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-assets/*/*